import 'package:flutter/material.dart';

const String fontName = 'Nunito';

const TextTheme textTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 57,
    height: 64 / 57,
  ),
  displayMedium: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 45,
    height: 52 / 45,
  ),
  displaySmall: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 36,
    height: 44 / 36,
  ),
  headlineLarge: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 32,
    height: 40 / 32,
  ),
  headlineMedium: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 28,
    height: 36 / 28,
  ),
  headlineSmall: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 24,
    height: 32 / 24,
  ),
  titleLarge: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 22,
    height: 28 / 22,
  ),
  titleMedium: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w500,
    fontSize: 16,
    height: 24 / 16,
  ),
  titleSmall: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 20 / 14,
  ),
  labelLarge: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 20 / 14,
  ),
  labelMedium: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w500,
    fontSize: 12,
    height: 16 / 12,
  ),
  labelSmall: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w500,
    fontSize: 11,
    height: 16 / 11,
  ),
  bodyLarge: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 16,
    height: 24 / 16,
  ),
  bodyMedium: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 14,
    height: 20 / 14,
  ),
  bodySmall: TextStyle(
    fontFamily: fontName,
    fontStyle: FontStyle.normal,
    fontWeight: FontWeight.w400,
    fontSize: 12,
    height: 16 / 12,
  ),
);
